
services:

  postgres:
    image: postgres:15
    container_name: refnet_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: referraldb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: refnet_mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: refnet_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  mongo_data: